### ISSUE TITLE
Template is not populated with template data

### ISSUE THREAD

**Issue by yawnana** [Sean-Bradley/SNMPWALK2ZABBIX#1]
Hello, thanks for putting together such a great script. 
On running the script, the OIDs are processed successfully, however the generated template file comes out empty in the icons section. 

![mstsc_tCH154VtjR](https://user-images.githubusercontent.com/20955032/171656193-c165d9d3-425f-4d1f-a8ae-24e60be7ff89.png)
![WindowsTerminal_UPchOvc0Wy](https://user-images.githubusercontent.com/20955032/171656200-05d5e3a3-b3ea-44ee-bd1c-0230f18f8ee1.png)

**Comment by Sean-Bradley** [comment]
does doing a snmpwalk with that OID give you a response
