### ISSUE TITLE
 IndexError: list index out of range

### ISSUE THREAD

**Issue by eubenietz** [Sean-Bradley/SNMPWALK2ZABBIX#10]
Hello,

Having a problem using the script.
When I used it always have the same issue:

**Traceback (most recent call last):
  File "snmpwalk2zabbix.py", line 174, in <module>
    name = mib.split("::")[1]
IndexError: list index out of range
**
snmpwalk works fine but when I executed the script get the problem.

How can I fix it?
Thanks in advance

**Comment by Sean-Bradley** [comment]
I can't reproduce your issue.

**Comment by eubenietz** [comment]
Hello,
So weird, a lunch the command and get the same issue.
Even changing the OID get more or fewer rows processed but never see the result.

Processing 67609 rows
Traceback (most recent call last):
  File "snmpwalk2zabbix.py", line 174, in <module>
    name = mib.split("::")[1]
IndexError: list index out of range

**Comment by Sean-Bradley** [comment]
Too bad. Im not paid to solve your issue
