### ISSUE TITLE
Help with a python error.

### ISSUE THREAD

**Issue by txurrispo** [Sean-Bradley/SNMPWALK2ZABBIX#11]
Hi!

I appreciated your work a lot. Thanks

I have a issue. Im triying th get a zabbix template for a Printer.
The snmpwak works fine. When i do the snmpwalk2zabbix.py i get this error:

`Processing 505 rows
Traceback (most recent call last):
  File "snmpwalk2zabbix.py", line 174, in <module>
    name = mib.split("::")[1]
IndexError: list index out of range`

Could you help me? 
Thanks
Kindest Regards.

**Comment by Sean-Bradley** [comment]
I cant reproduce your problem
