### ISSUE TITLE
Error: List Index Out of Range

### ISSUE THREAD

**Issue by Shorty365** [Sean-Bradley/SNMPWALK2ZABBIX#2]
Hi Sean,
Thanks for writing this nifty script. I was looking for such a script for a long time since developing custom SNMP-monitoring in Zabbix is tedious. I tried your scrip on my Kubuntu 20.04 machine, which has al updates against my TP-Link TL-SC3230N camera. The snmpwalk command gives me a whole bunch of information so the camera is responding to SNMP-requests. When I launch you script nothing seems to happen for a while and than is finishes with an error;
_Processing 532 rows
Traceback (most recent call last):
  File "/home/piet/snmpwalk2zabbix.py", line 174, in <module>
    name = mib.split("::")[1]
IndexError: list index out of range_

The command I issued, as root, was;
_python3 snmpwalk2zabbix.py public 192.168.xxx.yy 1.3.6_

Can you point me in the direction for a solution or is there something wrong in the script?

**Comment by Sean-Bradley** [comment]
I cant help you. Id need to have access to your SNMP device to know for sure.
I think 1.3.6 is too high an OID. Use something more specific. I don't know what that might be without see seeing the `snmpwalk` response which I guess is extremely large for a 1.3.6

**Comment by Shorty365** [comment]
Thanks for you swift reply. I'am just a hobbyist playing around with linux and various tools. If it helps you to make the script better and others for greater usability I enclosed the results of the snmpwalk, which is not that big. For me this is a nice to have, but not important enough to pay for.
[camera.smnp.txt](https://github.com/Sean-Bradley/SNMPWALK2ZABBIX/files/8844360/camera.smnp.txt)

**Comment by Shorty365** [comment]
Hi Sean,

Thanks a lot! My camera indeed uses an embedded Linux and aarhus is its hostname. I try to use the template later on and let you know the results. I have been trying to debug the error I got but my knowledge of Python is too limited to really understand what is going on.

**Comment by Shorty365** [comment]
Yeah, works! Data is flowing in. I have to adjust some things so the data becomes meaningful.
