### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by eevrenci** [Sean-Bradley/SNMPWALK2ZABBIX#3]
Hi,
Thank you for valuable sharing. I tried it at ubuntu 20.04 and debian 11 for different type of snmp devices. But I get this error message. Could you tell me what's wrong?

root@server24:~# python3 -V
Python 3.9.2
root@server24:~# python3 snmpwalk2zabbix.py community_Name snmp_IP 1.3.6.1.2.1
_Processing 991 rows
Traceback (most recent call last):
  File "/root/snmpwalk2zabbix.py", line 174, in <module>
    name = mib.split("::")[1]
IndexError: list index out of range_
root@server24:~#

**Comment by Sean-Bradley** [comment]
Read the licence
