### ISSUE TITLE
list index out of range "line 142" < if fullOidStringParts[8].upper().endswith("TABLE"): />

### ISSUE THREAD

**Issue by doubery** [Sean-Bradley/SNMPWALK2ZABBIX#4]
Hello, 

thank you very much for this script!!! 

I have a problem with this, is it possible you can support me?

What im doing wrong?

python3 snmpwalk2zabbix.py public 10.0.1.253 1.3.6.1.4.1.3652.3.3
Processing 576 rows
SINGLELINE-XFP-MIB::convSSLXFPMSlot.0: Unknown Object Identifier (Index out of range: 0 (convSSLXFPMSlot))
SINGLELINE-XFP-MIB::convSSLXFPMSlot.0: Unknown Object Identifier (Index out of range: 0 (convSSLXFPMSlot))
SINGLELINE-XFP-MIB::convSSLXFPMSlot.0: Unknown Object Identifier (Index out of range: 0 (convSSLXFPMSlot))
Traceback (most recent call last):
  File "/home/david/snmpwalk2zabbix.py", line 142, in <module>
    if fullOidStringParts[8].upper().endswith("TABLE"):
IndexError: list index out of range

thx

**Comment by Sean-Bradley** [comment]
Do know, sorry
