### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by daknie** [Sean-Bradley/SNMPWALK2ZABBIX#5]
I want to snmpwalk a Securepoint RC100/200 Firewall, but i will get this error massage:
```
Traceback (most recent call last):
  File "snmpwalk2zabbix.py", line 174, in <module>
    name = mib.split("::")[1]
IndexError: list index out of range
```
A normal _snmpwalk -v 2c -c public [deviceIP} 1.3.6.1.2_ works fine.

**Comment by ArshErgon** [comment]
what command you used?

**Comment by BMTTeam** [comment]
I have the same issue and while playing around the issue is with some of the responses. More specific, some OID responses might be not what is expected and mib.split()/name.split() are breaking the script. I didn't spend much time to troubleshoot in details - no time recent days :(. I would say that it's specific for some devices.

P.S.: It you provide bigger/longer OID as parameter, then it's working most of the time. I have to give it a try tomorrow with one HP MFP device (cannot remember now the model) that was causing this error. I'll come back with more details

Cheers,
-Tiho

**Comment by daknie** [comment]
> what command you used? or how you were running the project?

python3 snmpwalk2zabbix.py public [deviceIP] 1.3.6.1.2.1

**Comment by daknie** [comment]
I tested it with a similar model BlackDwarf G3, same issue.
A normal snmpwalk v3 gives me an output about 5.200 lines... without custom configuration/values on the firewall.

**Comment by BMTTeam** [comment]
Here is the test with MFU HP LaserJet MFP E72535
/snmpwalk2zabbix$ python3 snmpwalk2zabbix.py public 192.168.15.50 1.3.6.1
Timeout: No Response from 192.168.15.50
Processing 631 rows
Traceback (most recent call last):
  File "snmpwalk2zabbix.py", line 174, in <module>
    name = mib.split("::")[1]
IndexError: list index out of range

Now if specify different UID
/snmpwalk2zabbix$ python3 snmpwalk2zabbix.py public 192.168.15.50 1.3.6.1.4.1.11.2.3.9.1
Processing 43 rows
Done

and the template contains the following:
snmpwalk2zabbix$ cat template-my-template.xml 
<?xml version="1.0" encoding="UTF-8"?>
<zabbix_export>
    <version>6.0</version>
    <templates>
        <template>
            <uuid>81be1e1cae994f889987215102ec1f25</uuid>
            <template>my template SNMP</template>
            <name>my template SNMP</name>
            <description>Template built by SNMPWALK2ZABBIX script from https://github.com/Sean-Bradley/SNMPWALK2ZABBIX</description>
            <groups>
                <group>
                    <name>Templates</name>
                </group>
            </groups>
            <items>
        </template>
    </templates>

Here is the output from the snmpwalk (snmpwalk -c public -v 1 192.168.15.50):
[hp_printer.txt](https://github.com/Sean-Bradley/SNMPWALK2ZABBIX/files/9582038/hp_printer.txt)

Cheers,
-Tiho

**Comment by daknie** [comment]
No luck for me:
` python3 snmpwalk2zabbix.py public [deviceIP] 1.3.6.1.4.1.8072.3.2.10`

`Processing 2 rows
Unhandled data type [NO SUCH OBJECT AVAILABLE ON THIS AGENT AT THIS OID] so assigning TEXT
Traceback (most recent call last):
  File "snmpwalk2zabbix.py", line 102, in <module>
    value = oid_kvp[1].split(":")[1].strip()
IndexError: list index out of range`

But with an deeper OID 
`python3 snmpwalk2zabbix.py public [deviceIP] 1.3.6.1.4.1.8072.1.2.1.1.4.0`

`Processing 366 rowsDone`

**Comment by Sean-Bradley** [comment]
if you want support then your company needs to create a contract with me.
