### ISSUE TITLE
Not getting full list of OIDs

### ISSUE THREAD

**Issue by mariano-daniel** [Sean-Bradley/SNMPWALK2ZABBIX#6]
Hello! I am using the script as instructed for an HP Laserjet printer, but I cannot pull all of the OIDs. For example, `snmpwalk`output:

> SNMPv2-MIB::sysDescr.0 = STRING: HP ETHERNET MULTI-ENVIRONMENT,SN:VNC3G25503,FN:8E2APSZ,SVCID:29296,PID:HP Las
> erJet M15w
> SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.11.2.3.9.1
> DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (11709717) 1 day, 8:31:37.17
> SNMPv2-MIB::sysContact.0 = STRING: 
> SNMPv2-MIB::sysName.0 = STRING: NPIDA1759
> SNMPv2-MIB::sysLocation.0 = STRING: -34.746682, -58.34718
> SNMPv2-MIB::sysServices.0 = INTEGER: 72
> SNMPv2-MIB::sysORLastChange.0 = Timeticks: (0) 0:00: 

However Zabbix shows `SNMPv2-MIB::sysName.0`: 

![image](https://user-images.githubusercontent.com/60707523/191892844-b0f9e311-99ca-4a4e-87f6-8db83468199d.png)

But not `HOST-RESOURCES-MIB::hrDeviceDescr.1`

![image](https://user-images.githubusercontent.com/60707523/191893009-cc5d80a5-0fec-4c3c-90e1-cb2ebf199a09.png)

Also, the SNMPv2 MIBs that do not have a name are not picked up, for example `SNMPv2-SMI::mib-2.43.5.1.1.16.1 = STRING: "HP LaserJet M15w"`

Any help would be greatly appreciated!

**Comment by Sean-Bradley** [comment]
if you want support then your company needs to create a contract with me.
