### ISSUE TITLE
The Script is Returning an error

### ISSUE THREAD

**Issue by rohanrajnv** [Sean-Bradley/SNMPWALK2ZABBIX#8]
https://github.com/Sean-Bradley/SNMPWALK2ZABBIX/blob/e817348dacdf25edcf463b8295f2399a118efacc/snmpwalk2zabbix.py#L174
vsrsadmin@TIP-FAC-05:~$ sudo python3 snmpwalk2zabbix.py public 10.6.50.21 1.3.6.1.2.1
Processing 2589 rows
Traceback (most recent call last):
  File "snmpwalk2zabbix.py", line 174, in <module>
    name = mib.split("::")[1]
IndexError: list index out of range

The Snmp Walk command is successful
iso.3.6.1.2.1.1.1.0 = STRING: "Linux TIPAJSECSTO1 2.6.32-Cetus-202004151200 #1 SMP Wed Apr 15 12:05:07 CST 2020 x86_64"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.8072.3.2.10
iso.3.6.1.2.1.1.3.0 = Timeticks: (51337) 0:08:33.37
iso.3.6.1.2.1.1.4.0 = STRING: "admin"
---Lines Removed---
iso.3.6.1.2.1.88.1.4.3.1.3.6.95.115.110.109.112.100.95.109.116.101.84.114.105.103.103.101.114.82.105.115.105.110.103 = STRING: "_triggerFire"
iso.3.6.1.2.1.92.1.1.1.0 = Gauge32: 1000
iso.3.6.1.2.1.92.1.1.2.0 = Gauge32: 1440
iso.3.6.1.2.1.92.1.2.1.0 = Counter32: 0
iso.3.6.1.2.1.92.1.2.2.0 = Counter32: 0
iso.3.6.1.2.1.92.1.2.2.0 = No more variables left in this MIB View (It is past the end of the MIB tree)

**Comment by Sean-Bradley** [comment]
read the license.
